runtime: custom  # Use a custom runtime (Docker-based)
env: flex  # Flexible environment required for custom runtimes

service: default

handlers:
  - url: /.*
    script: auto

env_variables:
  DATABASE_URL: "mongodb+srv://udayomsrivastava:oHHFqeCziUf4gfgU@cluster0.vgn8n.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0"
  SECRET_KEY: "guiyfgc837tgf3iw87-012389764"
  SENDER_EMAIL: "web103856@gmail.com"
  SENDER_PASSWORD: "ipdtsisbfvjbrmkp"

manual_scaling:
  instances: 1

