name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry (GAR)
        run: |
          IMAGE=us-central1-docker.pkg.dev/velvety-ray-454718-b8/my-repo/my-app:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-service \
            --image us-central1-docker.pkg.dev/velvety-ray-454718-b8/my-repo/my-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }},secret_key=${{ secrets.SECRET_KEY }},sender_email=${{ secrets.SENDER_EMAIL }},sender_password=${{ secrets.SENDER_PASSWORD }},email_template=${{ secrets.EMAIL_TEMPLATE }},admin_email_template=${{ secrets.ADMIN_EMAIL_TEMPLATE }},LLM_ADDR=${{ secrets.LLM_ADDR }}"